version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_db_name
      MYSQL_USER: your_db_user
      MYSQL_PASSWORD: your_db_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    environment:
      - SRC_URL=https://www.vreg.be/sites/default/files/statistieken/v-testr_open_data_-_excl._btw.xlsx
      - DATABASE_URI=mysql+pymysql://your_db_user:your_db_password@db/your_db_name
    ports:
      - "5000:5000"
    depends_on:
      - db

  scripts:
    build: .
    command: python scripts/data_to_mysql.py
    environment:
      - SRC_URL=https://www.vreg.be/sites/default/files/statistieken/v-testr_open_data_-_excl._btw.xlsx
      - DATABASE_URI=mysql+pymysql://your_db_user:your_db_password@db/your_db_name
    depends_on:
      - db

volumes:
  db_data:
