name: Voer actions uit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Compose services
      run: docker-compose build

    - name: Pull Syft tool
      run: docker pull anchore/syft:latest

    - name: Generate SBOM for Docker Compose
      run: |
        docker-compose config > docker-compose-temp.yml
        docker run --rm -v $(pwd):/app -w /app anchore/syft:latest -o json docker-compose-temp.yml > sbom.json

    - name: Upload SBOM
      uses: actions/upload-artifact@v2
      with:
        name: sbom
        path: sbom.json
